"""create counter table

Revision ID: 69b5799b2f78
Revises: 
Create Date: 2021-08-29 14:12:07.042466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "69b5799b2f78"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("counter")
    # ### end Alembic commands ###
